spring:
  application:
    name: spring-webflux

  r2dbc:
    url: r2dbc:h2:mem:///flightdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

weather:
  api:
    key: ${WEATHER_API_KEY:demo-key}
    baseUrl: ${WEATHER_API_BASE_URL:http://api.weatherapi.com/v1}